FROM debian

RUN apt-get update && apt-get install -y apache2 php python3 && apt-get clean

ENV APACHE_LOCK_DIR="/var/lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE_RUN_USER="$USER"
ENV APACHE_RUN_GROUP="docker"
ENV APACHE_LOG_DIR="/var/log/apache2"

ADD . /

#&& apache2-foreground

# Use the default production configuration
#RUN mv "./php.ini" "$PHP_INI_DIR/php.ini"

LABEL version="0.1"

USER $USER

WORKDIR /home/$USER/.workspace/replay

VOLUME /var/www/html

ENTRYPOINT ["/usr/sbin/apachectl"]
CMD ["-D", "FOREGROUND"]

